name: 'Pizza Infra Workflow'

on:
  push:
    paths:
      - 'terraform/pizza-infra/**'
  pull_request:
    paths:
      - 'terraform/pizza-infra/**'

env:
  TF_LOG: INFO
  TF_INPUT: false

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is 
    # ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the preferred version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      run: terraform -chdir=terraform/pizza-infra init

    # Run a terraform fmt for push
    - name: Terraform Format
      id: fmt
      run: terraform -chdir=terraform/pizza-infra fmt -check

    # Run a terraform validate
    # Run even if formatting fails
    - name: Terraform Validate
      id: validate
      if: (success() || failure())
      run: terraform -chdir=terraform/pizza-infra validate
  
  deploy:
    name: 'Deploy Code'
    needs: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: 'AWS creds'
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Deploy with CodeDeploy using GitHub Commit
        run: |
          aws deploy create-deployment \
            --application-name pizza-luvrs \
            --deployment-group-name pizza-dev \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
        env:
          AWS_REGION: ap-southeast-2
